namespace ENetDotNet.Internal
{
    internal static class Constants
    {
        public const int
            ENET_HOST_RECEIVE_BUFFER_SIZE = 256 * 1024,
            ENET_HOST_SEND_BUFFER_SIZE = 256 * 1024,
            ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL = 1000,
            ENET_HOST_DEFAULT_MTU = 1400,
            ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE = 32 * 1024 * 1024,
            ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA = 32 * 1024 * 1024,

            ENET_PEER_DEFAULT_ROUND_TRIP_TIME = 500,
            ENET_PEER_DEFAULT_PACKET_THROTTLE = 32,
            ENET_PEER_PACKET_THROTTLE_SCALE = 32,
            ENET_PEER_PACKET_THROTTLE_COUNTER = 7,
            ENET_PEER_PACKET_THROTTLE_ACCELERATION = 2,
            ENET_PEER_PACKET_THROTTLE_DECELERATION = 2,
            ENET_PEER_PACKET_THROTTLE_INTERVAL = 5000,
            ENET_PEER_PACKET_LOSS_SCALE = (1 << 16),
            ENET_PEER_PACKET_LOSS_INTERVAL = 10000,
            ENET_PEER_WINDOW_SIZE_SCALE = 64 * 1024,
            ENET_PEER_TIMEOUT_LIMIT = 32,
            ENET_PEER_TIMEOUT_MINIMUM = 5000,
            ENET_PEER_TIMEOUT_MAXIMUM = 30000,
            ENET_PEER_PING_INTERVAL = 500,
            ENET_PEER_UNSEQUENCED_WINDOWS = 64,
            ENET_PEER_UNSEQUENCED_WINDOW_SIZE = 1024,
            ENET_PEER_FREE_UNSEQUENCED_WINDOWS = 32,
            ENET_PEER_RELIABLE_WINDOWS = 16,
            ENET_PEER_RELIABLE_WINDOW_SIZE = 0x1000,
            ENET_PEER_FREE_RELIABLE_WINDOWS = 8,

            ENET_PEER_FLAG_NEEDS_DISPATCH = (1 << 0),

            ENET_BUFFER_MAXIMUM = (1 + 2 * ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS),

            ENET_PROTOCOL_MINIMUM_MTU = 576,
            ENET_PROTOCOL_MAXIMUM_MTU = 4096,
            ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS = 32,
            ENET_PROTOCOL_MINIMUM_WINDOW_SIZE = 4096,
            ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE = 32768,
            ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT = 1,
            ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT = 255,
            ENET_PROTOCOL_MAXIMUM_PEER_ID = 0xFFF,
            ENET_PROTOCOL_MAXIMUM_PACKET_SIZE = 1024 * 1024 * 1024,
            ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT = 1024 * 1024,

            ENET_PROTOCOL_COMMAND_FLAG_ACKNOWLEDGE = 1 << 7,
            ENET_PROTOCOL_COMMAND_FLAG_UNSEQUENCED = 1 << 6,
            ENET_PROTOCOL_HEADER_FLAG_COMPRESSED = 1 << 14,
            ENET_PROTOCOL_HEADER_FLAG_SENT_TIME = 1 << 15,
            ENET_PROTOCOL_HEADER_FLAG_MASK = ENET_PROTOCOL_HEADER_FLAG_COMPRESSED |
                                             ENET_PROTOCOL_HEADER_FLAG_SENT_TIME,
            ENET_PROTOCOL_HEADER_SESSION_MASK = 3 << 12,
            ENET_PROTOCOL_HEADER_SESSION_SHIFT = 12,

            ENET_PROTOCOL_COMMAND_NONE = 0,
            ENET_PROTOCOL_COMMAND_ACKNOWLEDGE = 1,
            ENET_PROTOCOL_COMMAND_CONNECT = 2,
            ENET_PROTOCOL_COMMAND_VERIFY_CONNECT = 3,
            ENET_PROTOCOL_COMMAND_DISCONNECT = 4,
            ENET_PROTOCOL_COMMAND_PING = 5,
            ENET_PROTOCOL_COMMAND_SEND_RELIABLE = 6,
            ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE = 7,
            ENET_PROTOCOL_COMMAND_SEND_FRAGMENT = 8,
            ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED = 9,
            ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT = 10,
            ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE = 11,
            ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT = 12,
            ENET_PROTOCOL_COMMAND_COUNT = 13,
            ENET_PROTOCOL_COMMAND_MASK = 0x0F;
    }
}
